### ISSUE TITLE
Cannot destructure property 'message_id' of 'message' as it is undefined.

### ISSUE THREAD

**Issue by 0length** [denogram/denogram#1]
i had a problem suck like this 
````
 error: Uncaught TypeError: Cannot destructure property 'message_id' of 'message' as it is undefined.
    const { message_id: messageId, chat, text } = message as Message;
                        ^
    at Bot._handleUpdate (https://deno.land/x/telegram/bot.ts:100:25)
    at Array.forEach (<anonymous>)
    at Bot._handleUpdates (https://deno.land/x/telegram/bot.ts:109:13)
    at Bot._fetchUpdates (https://deno.land/x/telegram/bot.ts:118:10)
    at async Bot.launch (https://deno.land/x/telegram/bot.ts:137:5)

```
my deno version is 1.0.2

**Comment by stanislavstrelnikov** [comment]
It looks like you using [outdated denogram version](https://github.com/stanislavstrelnikov/deno-telegram), try to clear Deno cache

**Comment by 0length** [comment]
this is work thankyou
