### ISSUE TITLE
Uncaught Error: 404: Not Found

### ISSUE THREAD

**Issue by balinux** [denogram/denogram#6]
i got an error like this 

```
error: Uncaught Error: 404: Not Found
      throw new TelegramError(data.error_code, data.description);
            ^
    at Telegram.method (client.ts:29:13)
    at async Bot.launch (bot.ts:129:21)
```

my deno version : 1.1.2

**Comment by balinux** [comment]
i forgot to add dotenv 
https://deno.land/x/dotenv/README.md
